checkLoaded causes an stack-exceeded-error
Having checkLoaded in call itself recursivly causes an stack-exceeded-error:

RangeError: Maximum call stack size exceeded
    at checkLoaded ([...]/bower/ng-ckeditor/ng-ckeditor.js?22:20:25)
    at checkLoaded ([...]/bower/ng-ckeditor/ng-ckeditor.js?22:25:2)
    at checkLoaded ([...]/bower/ng-ckeditor/ng-ckeditor.js?22:25:2)
...